version: "3"
services:
  redis:
    image: "redis:alpine"
  app:
    depends_on:
      - redis
    build:
      context: .
    volumes:
      - ./app:/app
    env_file:
      - variables.env
  nginx:
    depends_on:
      - app
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log/nginx
